production: 
  class: \EuskalErrezetak\Model\RecipeTag
  fields: 
    recipeId: 
      title: _('Recipe id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \EuskalErrezetak\Mapper\Sql\Recipes
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name_${lang}
      default: true
    tagId: 
      title: _('Tag id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \EuskalErrezetak\Mapper\Sql\Tags
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name_${lang}
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
