production: 
  class: \EuskalErrezetak\Model\StaticPages
  fields: 
    title: 
      title: ngettext('Title', 'Titles', 1)
      type: text
      required: true
      default: true
    description: 
      title: ngettext('Description', 'Descriptions', 1)
      type: textarea
    status: 
      title: _('Statu')
      type: select
      source: 
        data: inline
        values: 
          'draft': _('draft')
          'published': _('published')
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
