production: 
  main: 
    log: 
      writerName: "Null"
      writerParams: 
    sitename: EuskalErrezetak
    logo: klear/images/klear.png
    year: 2015
    lang: eu
    langs: 
      eu: 
        title: Euskara
        language: eu
        locale: eu_ES
      es: 
        title: Español
        language: es
        locale: es_ES
    jqueryUI: 
      theme: redmond
    cssExtended: 
    actionHelpers: 
    auth: 
      adapter: Klear_Auth_Adapter_Basic
      title: _("Access denied")
      description: _("Insert your username")
    timezone: Europe/Madrid
    defaultCustomConfiguration:
         optionCollectionPlacement: both
  menu: 
    General: 
      title: _("Datuak kontsultatu/eguneratu")
      description: _("Main management")
      submenus: 
        CategoriesList: 
          title: ngettext('Category', 'Categories', 0)
          class: ui-silk-page-white-stack
          description: _("List of %s", ngettext('Category', 'Categories', 0))
        RecipesList: 
          title: ngettext('Recipe', 'Recipes', 0)
          class: ui-silk-book-open
          description: _("List of %s", ngettext('Recipe', 'Recipes', 0))
        TagsList: 
          title: ngettext('Tag', 'Tags', 0)
          class: ui-silk-tag-blue
          description: _("List of %s", ngettext('Tag', 'Tags', 0))
    # BesteMenuBat:
    #   title: _("Beste Menu Bat")
    #   description: _("Hau testu da")
    #   submenus: 
    #     CategoriesList: 
    #       title: ngettext('Category', 'Categories', 0)
    #       class: ui-silk-text-list-bullets
    #       description: _("List of %s", ngettext('Category', 'Categories', 0))
    Klear: 
      title: _("Ezarpenak")
      description: _("Ezarpen orokorrak kudeatzeko atala")
      submenus: 
        Dashboard:
          default: true
          title: Kontrol-panela
          class: ui-silk-bricks
          description: _("Entitate guztien ikuspegi orokorra")
        KlearUsersList: 
          title: _("Klear erabiltzaileak")
          class: ui-silk-user-gray
          description: _("Klear erabiltzaileen zerrenda")
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
