#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: recipesList_screen
  screens: 
    recipesList_screen: &recipesList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Recipes
      title: _("List of %s %2s", ngettext('Recipe', 'Recipes', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            recipesEdit_screen: true
          dialogs: 
            recipesDel_dialog: true
          default: recipesEdit_screen
        blacklist:
          directions: true
          ingredients: true
          picture: true
      options: 
        title: _("Options")
        screens: 
          recipesNew_screen: true
        dialogs: 
          recipesDel_dialog: true
      preconfiguredFilters:
        searchByCategory6:
          title: _("Betiko Errezetak")
          field: RecipeCategory
          value: "6"
          description: _("Utiliza este pre filtrado para buscar recetas de la categoría Betiko Errezetak")
        searchByCategory9:
          title: _("Pintxoak")
          field: RecipeCategory
          value: "9"
          description: _("Utiliza este pre filtrado para buscar recetas de la categoría Pintxoak")
        searchByCategory10:
          title: _("Edariak")
          field: RecipeCategory
          value: "10"
          description: _("Utiliza este pre filtrado para buscar recetas de la categoría Edariak")
        searchByCategory11:
          title: _("Bertoko produktuekin")
          field: RecipeCategory
          value: "11"
          description: _("Utiliza este pre filtrado para buscar recetas de la categoría Bertoko produktuekin")
        searchByPeople2:
          title: _("2 pertsonentzako")
          field: people
          value: "2"
          description: _("Utiliza este pre filtrado para buscar recetas para 2 personas")
        searchByPeople4:
          title: _("4 pertsonentzako")
          field: people
          value: "4"
          description: _("Utiliza este pre filtrado para buscar recetas para 4 personas")
        searchByPeople6:
          title: _("6 pertsonentzako")
          field: people
          value: "6"
          description: _("Utiliza este pre filtrado para buscar recetas para 6 personas")
        searchByDifficultyEasy:
          title: _("Easy")
          field: difficulty
          value: "easy"
          description: _("Utiliza este pre filtrado para buscar recetas fáciles")
        searchByDifficultyMedium:
          title: _("Medium")
          field: difficulty
          value: "medium"
          description: _("Utiliza este pre filtrado para buscar recetas de dificultad mediana")
        searchByDifficultyHard:
          title: _("Easy")
          field: difficulty
          value: "hard"
          description: _("Utiliza este pre filtrado para buscar recetas difíciles")
    recipesNew_screen: &recipesNew_screenLink 
      <<: *Recipes
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Recipe', 'Recipes', 1))
      shortcutOption: N
      fullWidth: true
      fixedPositions:
        group0:
          fields:
            picture: 1
            name: 1
        group1:
          label: _('Informazio orokorra') # El título no es obligatorio
          fields:
            time: 1
            difficulty: 1
            cost: 1
            people: 1
        group2:
          fields:
            ingredients: 1
        group3:
          fields:
            directions: 1
        group4:
          label: _('Kategoria eta etiketak')
          fields:
            RecipeCategory: 1
            RecipeTag: 1
    recipesEdit_screen: &recipesEdit_screenLink 
      <<: *Recipes
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Recipe', 'Recipes', 1), "[format| (%item%)]")
      fullWidth: true
      fixedPositions:
        group0:
          fields:
            picture: 1
            name: 1
        group1:
          label: _('Informazio orokorra') # El título no es obligatorio
          fields:
            time: 1
            difficulty: 1
            cost: 1
            people: 1
        group2:
          fields:
            ingredients: 1
        group3:
          fields:
            directions: 1
        group4:
          label: _('Kategoria eta etiketak')
          fields:
            RecipeCategory: 1
            RecipeTag: 1
  dialogs: 
    recipesDel_dialog: &recipesDel_dialogLink 
      <<: *Recipes
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Recipe', 'Recipes', 1))
      description: _("Do you want to delete this %s?", ngettext('Recipe', 'Recipes', 1))
      message: _("%s successfully deleted.", ngettext('Recipe', 'Recipes', 1))
      multiItem: 1
      labelOnList: 1
  commands: 
    PictureDownload_command: 
      <<: *Recipes
      controller: File
      action: force-download
      mainColumn: picture
    PictureUpload_command: 
      <<: *Recipes
      controller: File
      action: upload
      mainColumn: picture
    PicturePreview_command: 
      <<: *Recipes
      controller: File
      action: preview
      mainColumn: picture
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
