#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: categoriesList_screen
  screens: 
    categoriesList_screen: &categoriesList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Categories
      title: _("List of %s %2s", ngettext('Category', 'Categories', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            categoriesEdit_screen: true
          dialogs: 
            categoriesDel_dialog: true
          default: categoriesEdit_screen
      options: 
        title: _("Options")
        screens: 
          categoriesNew_screen: true
        dialogs: 
          categoriesDel_dialog: true
    categoriesNew_screen: &categoriesNew_screenLink 
      <<: *Categories
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Category', 'Categories', 1))
      shortcutOption: N
    categoriesEdit_screen: &categoriesEdit_screenLink 
      <<: *Categories
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Category', 'Categories', 1), "[format| (%item%)]")
  dialogs: 
    categoriesDel_dialog: &categoriesDel_dialogLink 
      <<: *Categories
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Category', 'Categories', 1))
      description: _("Do you want to delete this %s?", ngettext('Category', 'Categories', 1))
      message: _("%s successfully deleted.", ngettext('Category', 'Categories', 1))
      multiItem: 1
      labelOnList: 1
  commands: 
    ImgDownload_command: 
      <<: *Categories
      controller: File
      action: force-download
      mainColumn: img
    ImgUpload_command: 
      <<: *Categories
      controller: File
      action: upload
      mainColumn: img
    ImgPreview_command: 
      <<: *Categories
      controller: File
      action: preview
      mainColumn: img
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
