#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: recipesList_screen
  screens: 
    recipesList_screen: &recipesList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Recipes
      title: _("List of %s %2s", ngettext('Recipe', 'Recipes', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            recipesEdit_screen: true
          dialogs: 
            recipesDel_dialog: true
          default: recipesEdit_screen
      options: 
        title: _("Options")
        screens: 
          recipesNew_screen: true
        dialogs: 
          recipesDel_dialog: true
    recipesNew_screen: &recipesNew_screenLink 
      <<: *Recipes
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Recipe', 'Recipes', 1))
      shortcutOption: N
    recipesEdit_screen: &recipesEdit_screenLink 
      <<: *Recipes
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Recipe', 'Recipes', 1), "[format| (%item%)]")
  dialogs: 
    recipesDel_dialog: &recipesDel_dialogLink 
      <<: *Recipes
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Recipe', 'Recipes', 1))
      description: _("Do you want to delete this %s?", ngettext('Recipe', 'Recipes', 1))
      message: _("%s successfully deleted.", ngettext('Recipe', 'Recipes', 1))
      multiItem: 1
      labelOnList: 1
  commands: 
    PictureDownload_command: 
      <<: *Recipes
      controller: File
      action: force-download
      mainColumn: picture
    PictureUpload_command: 
      <<: *Recipes
      controller: File
      action: upload
      mainColumn: picture
    PicturePreview_command: 
      <<: *Recipes
      controller: File
      action: preview
      mainColumn: picture
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
