#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: staticPagesList_screen
  screens: 
    staticPagesList_screen: &staticPagesList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *StaticPages
      title: _("List of %s %2s", ngettext('Static page', 'Static pages', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            staticPagesEdit_screen: true
          dialogs: 
            staticPagesDel_dialog: true
          default: staticPagesEdit_screen
      options: 
        title: _("Options")
        screens: 
          staticPagesNew_screen: true
        dialogs: 
          staticPagesDel_dialog: true
    staticPagesNew_screen: &staticPagesNew_screenLink 
      <<: *StaticPages
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Static page', 'Static pages', 1))
      shortcutOption: N
    staticPagesEdit_screen: &staticPagesEdit_screenLink 
      <<: *StaticPages
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Static page', 'Static pages', 1), "[format| (%item%)]")
  dialogs: 
    staticPagesDel_dialog: &staticPagesDel_dialogLink 
      <<: *StaticPages
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Static page', 'Static pages', 1))
      description: _("Do you want to delete this %s?", ngettext('Static page', 'Static pages', 1))
      message: _("%s successfully deleted.", ngettext('Static page', 'Static pages', 1))
      multiItem: 1
      labelOnList: 1
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
