production: 
  class: \EuskalErrezetak\Model\SocialNetworks
  fields: 
  
    title: 
      title: _('Titulo')
      type: text
      required: true
      default: true
      
    url: 
      title: _('Url')
      type: text
      required: true
      
    status: 
      title: _('Estado')
      type: select
      source: 
        data: inline
        values: 
          'draft': _('Borrador')
          'published': _('Publicada')
          
    icon: 
      title: _('Icono')
      type: text
      
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production