production: 
  class: \EuskalErrezetak\Model\Tags
  fields: 
    name: 
      title: ngettext('Name', 'Names', 1)
      type: text
      required: true
      default: true
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
